import { Head, router, usePage } from '@inertiajs/react';
import { useState } from 'react';
import CheckoutLayout from '@/app/layouts/CheckoutLayout';

const money = value => `৳${Number(value || 0).toLocaleString('en-BD', { maximumFractionDigits: 2 })}`;

export default function CheckoutPage({ items = [], subtotal = 0 }) {
    const { auth } = usePage().props;
    const [data, setData] = useState({ customer_name: auth?.user?.name || '', phone: auth?.user?.phone || '', email: auth?.user?.email || '', address: '', city: '', note: '', payment_method: 'cod' });
    const [errors, setErrors] = useState({});
    const [processing, setProcessing] = useState(false);
    const set = (key, value) => setData(current => ({ ...current, [key]: value }));
    const submit = event => { event.preventDefault(); setProcessing(true); setErrors({}); router.post(route('storefront.checkout.place-order'), data, { onError: setErrors, onFinish: () => setProcessing(false) }); };
    return <CheckoutLayout><Head title="Checkout" /><div className="grid gap-7 lg:grid-cols-[1fr_340px]"><form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-6"><h1 className="text-2xl font-bold">Delivery information</h1><p className="mt-1 text-sm text-slate-500">Enter your details to place the order.</p><div className="mt-6 grid gap-4 sm:grid-cols-2">{[['customer_name', 'Full name'], ['phone', 'Phone number'], ['email', 'Email (optional)'], ['city', 'City / area']].map(([key, label]) => <label key={key} className="text-sm font-semibold">{label}<input value={data[key]} type={key === 'email' ? 'email' : 'text'} onChange={event => set(key, event.target.value)} className="mt-2 w-full rounded-xl border-slate-300" />{errors[key] && <small className="mt-1 block text-rose-600">{errors[key]}</small>}</label>)}</div><label className="mt-4 block text-sm font-semibold">Full delivery address<textarea value={data.address} onChange={event => set('address', event.target.value)} className="mt-2 min-h-24 w-full rounded-xl border-slate-300" />{errors.address && <small className="mt-1 block text-rose-600">{errors.address}</small>}</label><label className="mt-4 block text-sm font-semibold">Order note (optional)<textarea value={data.note} onChange={event => set('note', event.target.value)} className="mt-2 min-h-20 w-full rounded-xl border-slate-300" /></label><section className="mt-6 rounded-xl border border-violet-200 bg-violet-50 p-4"><h2 className="font-bold">Payment method</h2><label className="mt-3 flex items-center gap-2 text-sm font-semibold"><input type="radio" checked={data.payment_method === 'cod'} onChange={() => set('payment_method', 'cod')} className="text-violet-600 focus:ring-violet-500" />Cash on Delivery</label></section><button disabled={processing} className="mt-6 h-12 w-full rounded-xl bg-violet-600 font-bold text-white disabled:opacity-60">{processing ? 'Placing order...' : 'Place order'}</button></form><aside className="h-fit rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">Your order</h2><div className="mt-5 space-y-4 border-b border-slate-200 pb-4">{items.map(item => <div key={item.product_id} className="flex justify-between gap-3 text-sm"><span className="min-w-0 text-slate-600"><b className="block truncate text-slate-900">{item.title}</b>× {item.quantity}</span><b>{money(item.line_total)}</b></div>)}</div><div className="mt-4 flex justify-between text-lg font-bold"><span>Total</span><span>{money(subtotal)}</span></div></aside></div></CheckoutLayout>;
}
