import { Head, router } from '@inertiajs/react';
import { MessageCircleQuestion, Star, Trash2 } from 'lucide-react';
import { useState } from 'react';
import AdminLayout from '@/app/layouts/AdminLayout';
const statuses=['pending','approved','rejected','spam'];
export default function ReviewsIndex({reviews,questions}) {
 const [tab,setTab]=useState('reviews'); const rows=tab==='reviews'?reviews.data:questions.data;
 const save=(item,status,answer='')=>router.patch(tab==='reviews'?route('reviews.update',item.id):route('questions.update',item.id),tab==='reviews'?{status,admin_reply:answer}:{status,answer},{preserveScroll:true});
 const remove=(item)=>confirm(`Delete this ${tab==='reviews'?'review':'question'}?`)&&router.delete(tab==='reviews'?route('reviews.destroy',item.id):route('questions.destroy',item.id),{preserveScroll:true});
 return <AdminLayout><Head title="Reviews & Q&A"/><main className="-mx-4 -my-6 min-h-screen bg-[#f8f7fa] p-6 lg:-mx-8 lg:-my-8 lg:p-8"><div className="mx-auto max-w-7xl"><p className="text-sm font-semibold text-violet-600">Products</p><h1 className="text-2xl font-bold">Reviews & Questions</h1><div className="mt-6 flex gap-2"><button onClick={()=>setTab('reviews')} className={`rounded-lg px-4 py-2 font-semibold ${tab==='reviews'?'bg-violet-600 text-white':'bg-white'}`}><Star className="mr-2 inline size-4"/>Reviews</button><button onClick={()=>setTab('questions')} className={`rounded-lg px-4 py-2 font-semibold ${tab==='questions'?'bg-violet-600 text-white':'bg-white'}`}><MessageCircleQuestion className="mr-2 inline size-4"/>Q&A</button></div><div className="mt-4 overflow-x-auto rounded-xl border bg-white"><table className="min-w-full"><thead><tr><th className="px-4 py-3 text-left">Product</th><th className="px-4 py-3 text-left">Customer</th><th className="px-4 py-3 text-left">Content</th><th className="px-4 py-3 text-left">Status</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{rows.map(item=><ModerationRow key={item.id} item={item} type={tab} save={save} remove={remove}/>)}</tbody></table>{!rows.length&&<p className="p-12 text-center text-sm text-slate-500">Nothing to moderate.</p>}</div></div></main></AdminLayout>;
}
function ModerationRow({item,type,save,remove}){const [text,setText]=useState(type==='reviews'?item.admin_reply||'':item.answer||'');return <tr className="border-t align-top"><td className="px-4 py-4 font-semibold">{item.product?.title}</td><td className="px-4 py-4">{item.customer_name}</td><td className="max-w-xl px-4 py-4"><b>{type==='reviews'&&`${item.rating}★ ${item.title||''}`}</b><p className="mt-1 text-sm text-slate-600">{type==='reviews'?item.description:item.question}</p><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={type==='reviews'?'Admin reply':'Answer'} className="mt-3 w-full rounded-lg border-slate-300 text-sm"/></td><td className="px-4 py-4"><select defaultValue={item.status} onChange={e=>save(item,e.target.value,text)} className="rounded-lg border-slate-300 text-sm">{statuses.map(s=><option key={s}>{s}</option>)}</select></td><td className="px-4 py-4"><div className="flex gap-2"><button onClick={()=>save(item,item.status,text)} className="rounded-lg bg-violet-600 px-3 py-2 text-xs font-semibold text-white">Save</button><button onClick={()=>remove(item)} className="grid size-8 place-items-center rounded-lg bg-rose-50 text-rose-600"><Trash2 className="size-4"/></button></div></td></tr>}
