import LocationFields from './LocationFields';
import { useState } from 'react';
import { Send } from 'lucide-react';
import { api, button, panel } from './ui';
export default function BulkCourier({orders,selected,setSelected}) {
    const [fields,setFields]=useState({}),[open,setOpen]=useState(false),[couriers,setCouriers]=useState([]),[courier,setCourier]=useState(''),[results,setResults]=useState([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0);
    const selectedOrders=orders.filter(o=>selected.includes(o.id));
    return <div className="contents"><button type="button" className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-violet-200 bg-violet-50 px-4 text-sm font-semibold text-violet-700 transition hover:bg-violet-100 dark:border-violet-800 dark:bg-violet-950/50 dark:text-violet-200" onClick={async()=>{setOpen(!open);if(orders.length)try{setCouriers((await api(route('couriers.order',orders[0].id))).couriers);}catch(e){setResults([{message:e.message}]);}}}><Send className="size-4"/>Send selected to courier{selected.length>0&&<span className="rounded-full bg-violet-600 px-2 py-0.5 text-[11px] text-white">{selected.length}</span>}</button>{open&&<div className={panel+' col-span-full mt-1'}><p className="mb-3 text-sm text-slate-500">Select confirmed orders on this page. Complete Pathao district/zone/area below for each selected order.</p><div className="mb-4 grid max-h-64 gap-2 overflow-auto sm:grid-cols-3">{orders.map(o=><label key={o.id} className="flex gap-2 text-sm"><input type="checkbox" disabled={!['confirmed','processing','ready_to_ship'].includes(o.statusKey)} checked={selected.includes(o.id)} onChange={e=>setSelected(e.target.checked?[...selected,o.id]:selected.filter(id=>id!==o.id))}/>{o.number} — {o.customer}</label>)}</div><select value={courier} onChange={e=>setCourier(e.target.value)}><option value="">Select Courier</option>{couriers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{couriers.find(c=>String(c.id)===courier)?.slug==='pathao'&&selectedOrders.map(o=><div key={o.id} className="my-3 rounded border p-3"><p>{o.number} — {o.delivery}</p><LocationFields courierId={courier} value={fields[o.id]||{}} onChange={value=>setFields(current=>({...current,[o.id]:value}))}/></div>)}<button type="button" disabled={busy||!courier||!selectedOrders.length} className={button+' ml-3'} onClick={async()=>{setBusy(true);setResults([]);setProgress(0);try{for(const [index,o] of selectedOrders.entries()){try{const response=await api(route('couriers.book'),{courier_id:courier,orders:[{id:o.id,fields:fields[o.id]||{}}]});setResults(current=>[...current,...response.results]);}catch(e){setResults(current=>[...current,{order_id:o.id,message:e.message+' Check booking details before retrying.'}]);}setProgress(index+1);}}finally{setBusy(false);}}}>{busy?`Sending… ${progress} / ${selectedOrders.length}`:`Confirm Booking (${selectedOrders.length})`}</button>{results.map((r,i)=><p key={i} className="mt-2 text-sm">{r.order_id?`Order ${r.order_id}: `:''}{r.message}</p>)}</div>}</div>;
}
