import BookingActions from './BookingActions';
import { useEffect, useState } from 'react';
import { api, Field, button, panel } from './ui';
export default function OrderCourier({ orderId }) {
    const [state,setState]=useState(null),[courierId,setCourierId]=useState(''),[fields,setFields]=useState({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[cities,setCities]=useState([]),[zones,setZones]=useState([]),[areas,setAreas]=useState([]);
    const load=()=>api(route('couriers.order',orderId)).then(data=>{setState(data);setFields(current=>Object.keys(current).length?current:data.defaults);});
    useEffect(()=>{load().catch(e=>setMessage(e.message));},[orderId]);
    useEffect(()=>{if(!state?.bookings.some(b=>['queued','submitting'].includes(b.status)))return;const timer=setInterval(()=>load().catch(()=>{}),4000);return()=>clearInterval(timer);},[state?.bookings]);
    const courier=state?.couriers.find(c=>String(c.id)===String(courierId));
    const locations=async(type,parent)=>{try{return await api(route('couriers.locations',courierId)+`?type=${type}${parent?'&parent='+parent:''}`);}catch(e){setMessage(e.message);return [];}};
    useEffect(()=>{setCities([]);setZones([]);setAreas([]);if(courier?.slug==='pathao')locations('cities').then(setCities);},[courierId]);
    const action=async(fn)=>{setBusy(true);setMessage('');try{const result=await fn();setMessage(result.message||result.results?.map(r=>r.message).join(' '));await load();}catch(e){setMessage(e.message);}finally{setBusy(false);}};
    return <section className={panel}><h2 className="mb-4">Courier / Delivery</h2>{message&&<p role="status" className="mb-4 rounded-lg bg-violet-50 p-3 text-sm text-violet-700">{message}</p>}
        {state&&<><div className="space-y-3">{state.bookings.map(b=><article key={b.id} className="rounded-lg border p-4"><b>{b.courier.name}</b><p className="mt-1 text-sm">{b.status.replaceAll('_',' ')}{b.sandbox_mode?' · Sandbox':''}</p><p className="text-xs text-slate-500">Reference: {b.reference}<br/>Consignment: {b.consignment_id||'Awaiting confirmation'}<br/>Tracking: {b.tracking_code||'—'}</p>{b.error&&<p className="my-2 text-sm text-amber-700">{b.error}</p>}<div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} className="rounded border px-3 py-2 text-xs" onClick={()=>action(()=>api(route('couriers.refresh',b.id),{}))}>Track / Refresh Status</button>{b.consignment_id&&<a className="rounded border px-3 py-2 text-xs" target="_blank" rel="noopener noreferrer" href={route('couriers.label',b.id)}>Print Courier Label</a>}<button disabled={busy} className="rounded border px-3 py-2 text-xs" onClick={()=>action(()=>api(route('couriers.cancel',b.id),{}))}>Cancel Booking</button></div><details className="mt-3 text-xs"><summary>View courier details</summary><p className="my-2">COD: ৳{b.cod_amount} · Courier charge: {b.delivery_charge??'Not supplied'} · Booked: {b.booked_at||'—'}</p>{b.logs.map((log,i)=><p key={i}>{log.created_at} — {log.status} ({log.api_status})</p>)}<pre className="mt-3 max-h-48 overflow-auto whitespace-pre-wrap">{JSON.stringify(b.response_data,null,2)}</pre></details><BookingActions booking={b} onDone={load}/></article>)}</div>
        {!state.bookings.some(b=>b.active_order_id)&&<form className="mt-4 space-y-4" onSubmit={e=>{e.preventDefault();action(()=>api(route('couriers.book'),{courier_id:courierId,orders:[{id:orderId,fields}]}));}}><Field label="Select Courier"><select required value={courierId} onChange={e=>{setCourierId(e.target.value);setFields({...fields,city_id:'',zone_id:'',area_id:''});}}><option value="">Select active courier</option>{state.couriers.map(c=><option key={c.id} value={c.id}>{c.name}{c.sandbox_mode?' (Sandbox)':''}</option>)}</select></Field><div className="grid gap-4 sm:grid-cols-2">{['recipient_name','phone','address','district','weight','instruction'].map(key=><Field label={key.replaceAll('_',' ')} key={key}><input required={!['instruction','district'].includes(key)} type={key==='weight'?'number':'text'} step={key==='weight'?'.1':undefined} value={fields[key]??''} onChange={e=>setFields({...fields,[key]:e.target.value})}/></Field>)}<Field label="Delivery type"><select value={fields.delivery_type||48} onChange={e=>setFields({...fields,delivery_type:e.target.value})}><option value="48">Normal delivery</option>{courier?.slug==='pathao'&&<option value="12">On demand</option>}</select></Field>{courier?.slug==='pathao'&&<>{[['District / City','city_id',cities,'city'],['Zone','zone_id',zones,'zone'],['Area','area_id',areas,'area']].map(([label,key,options,prefix])=><Field key={key} label={label}><select required value={fields[key]||''} onChange={async e=>{const value=e.target.value;setFields({...fields,[key]:value,...(key==='city_id'?{zone_id:'',area_id:''}:key==='zone_id'?{area_id:''}:{})});if(key==='city_id'){setAreas([]);setZones(await locations('zones',value));}if(key==='zone_id')setAreas(await locations('areas',value));}}><option value="">Select {label}</option>{options.map(o=><option key={o[prefix+'_id']} value={o[prefix+'_id']}>{o[prefix+'_name']}</option>)}</select></Field>)}</>}</div><p className="text-sm text-slate-500">COD: ৳{state.defaults.cod_amount} · Customer delivery charge: ৳{state.defaults.customer_delivery_charge}</p><button disabled={busy||!courierId} className={button}>{busy?'Submitting…':'Send to Courier'}</button><p className="text-xs text-slate-500">Courier charge is shown when returned by the provider.</p></form>}</>}
    </section>;
}
