import { Head, Link, useForm } from '@inertiajs/react';
import { Save, ShieldCheck, UserRound } from 'lucide-react';
import AdminLayout from '@/app/layouts/AdminLayout';
import { ErrorText, input, panel } from '@/app/modules/access/components';

export default function UserForm({ adminUser, roles }) {
    const editing=Boolean(adminUser); const {data,setData,post,put,processing,errors}=useForm({name:adminUser?.name||'',email:adminUser?.email||'',phone:adminUser?.phone||'',password:'',password_confirmation:'',is_active:adminUser?.isActive??true,roles:adminUser?.roles||[]});
    const toggle=(id)=>setData('roles',data.roles.includes(id)?data.roles.filter(item=>item!==id):[...data.roles,id]);
    const submit=(event)=>{event.preventDefault();editing?put(route('admin-users.update',adminUser.id)):post(route('admin-users.store'));};
    return <AdminLayout><Head title={editing?'Edit admin user':'Add admin user'}/><form onSubmit={submit} className="mx-auto max-w-5xl space-y-6"><div><p className="text-sm font-bold text-violet-600">Access control</p><h1 className="mt-1 text-3xl font-black text-slate-950">{editing?'Edit admin user':'Add admin user'}</h1><p className="mt-2 text-sm text-slate-500">Account information and role assignment are managed together.</p></div>
        <section className={`${panel} p-6`}><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-violet-100 text-violet-700"><UserRound className="size-5"/></span><div><h2 className="text-lg font-bold">Account details</h2><p className="text-sm text-slate-500">Use a unique email and a strong password.</p></div></div><div className="mt-6 grid gap-5 md:grid-cols-2"><label className="text-sm font-bold">Full name<input className={input} value={data.name} onChange={e=>setData('name',e.target.value)} required/><ErrorText>{errors.name}</ErrorText></label><label className="text-sm font-bold">Email<input className={input} type="email" value={data.email} onChange={e=>setData('email',e.target.value)} required/><ErrorText>{errors.email}</ErrorText></label><label className="text-sm font-bold">Phone<input className={input} value={data.phone} onChange={e=>setData('phone',e.target.value)} placeholder="Optional"/><ErrorText>{errors.phone}</ErrorText></label><label className="flex items-center gap-3 self-end rounded-lg border border-slate-200 p-3 text-sm font-bold"><input type="checkbox" checked={data.is_active} onChange={e=>setData('is_active',e.target.checked)} className="rounded border-slate-300 text-violet-600"/>Active account</label><label className="text-sm font-bold">Password {editing&&<span className="font-normal text-slate-400">(leave blank to keep)</span>}<input className={input} type="password" value={data.password} onChange={e=>setData('password',e.target.value)} required={!editing}/><ErrorText>{errors.password}</ErrorText></label><label className="text-sm font-bold">Confirm password<input className={input} type="password" value={data.password_confirmation} onChange={e=>setData('password_confirmation',e.target.value)} required={!editing}/></label></div></section>
        <section className={`${panel} p-6`}><div className="flex items-center gap-3"><ShieldCheck className="size-6 text-violet-600"/><div><h2 className="text-lg font-bold">Assign roles</h2><p className="text-sm text-slate-500">The user receives the combined permissions of selected roles.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2">{roles.map(role=><label key={role.id} className={`flex cursor-pointer gap-3 rounded-xl border p-4 transition ${data.roles.includes(role.id)?'border-violet-400 bg-violet-50':'border-slate-200 hover:border-violet-200'}`}><input type="checkbox" checked={data.roles.includes(role.id)} onChange={()=>toggle(role.id)} className="mt-1 rounded border-slate-300 text-violet-600"/><span><b className="block text-sm text-slate-900">{role.name}</b><span className="mt-1 block text-xs leading-5 text-slate-500">{role.description||'Custom access role'} · {role.users} users</span></span></label>)}</div><ErrorText>{errors.roles}</ErrorText></section>
        <div className="flex justify-end gap-3"><Link href={route('admin-users.index')} className="inline-flex h-11 items-center rounded-lg border border-slate-300 px-5 text-sm font-bold">Cancel</Link><button disabled={processing} className="inline-flex h-11 items-center gap-2 rounded-lg bg-violet-600 px-5 text-sm font-bold text-white disabled:opacity-50"><Save className="size-4"/>{processing?'Saving...':'Save user'}</button></div>
    </form></AdminLayout>;
}
