import { Head, Link, router } from '@inertiajs/react';
import { Eye, Image, Pencil, Plus, Search, Trash2, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import IconButton from '@/app/design-system/components/IconButton';
import AdminLayout from '@/app/layouts/AdminLayout';

const money = (value) => `৳${Number(value || 0).toLocaleString('en-BD', { minimumFractionDigits: 2 })}`;
const actionClass = 'category-table__action rounded-full border-0 bg-[#e7edf5] text-slate-600 hover:bg-violet-100 hover:text-violet-700';

function ProductActions({ product, onView, onDelete }) {
    return <div className="flex items-center justify-end gap-1.5"><IconButton icon={Eye} iconClassName="!size-4" label={`View ${product.title}`} onClick={() => onView(product)} className={actionClass} /><IconButton icon={Pencil} iconClassName="!size-4" label={`Edit ${product.title}`} onClick={() => { window.location.href = `${route('inventories.products.create')}?edit=${product.id}`; }} className={actionClass} /><IconButton icon={Trash2} iconClassName="!size-4" label={`Delete ${product.title}`} onClick={() => onDelete(product)} className={`${actionClass} hover:!bg-red-50 hover:!text-red-600`} /></div>;
}

function ViewModal({ product, onClose }) {
    useEffect(() => {
        if (!product) return;
        const details = document.querySelector('.fixed.inset-0.z-50 dl');
        if (!details || details.dataset.fullProductInfo) return;
        const values = [
            ['Brand', product.brand], ['Barcode', product.barcode], ['Model', product.model], ['Manufacturer', product.manufacturer], ['Country of origin', product.countryOfOrigin], ['Weight', product.weight], ['Dimensions', product.dimensions], ['Warranty', product.warranty], ['Estimated delivery', product.estimatedDelivery], ['Inside Dhaka delivery', product.deliveryInsideDhaka !== null && product.deliveryInsideDhaka !== undefined ? money(product.deliveryInsideDhaka) : null], ['Outside Dhaka delivery', product.deliveryOutsideDhaka !== null && product.deliveryOutsideDhaka !== undefined ? money(product.deliveryOutsideDhaka) : null], ['Payment methods', product.paymentMethods], ['SEO title', product.seoTitle], ['Meta description', product.metaDescription], ['Short description', product.shortDescription], ['Description', product.description?.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim()], ['Return policy', product.returnPolicy], ['Replacement policy', product.replacementPolicy],
        ].filter(([, value]) => value);
        values.forEach(([label, value]) => { const item = document.createElement('div'); item.innerHTML = `<dt class="text-slate-500">${label}</dt><dd class="mt-1 font-semibold">${value}</dd>`; details.append(item); });
        details.dataset.fullProductInfo = 'true';
    }, [product]);
    if (!product) return null;
    return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-sm font-semibold text-violet-600">Product details</p><h2 className="mt-1 text-xl font-bold">{product.title}</h2></div><IconButton icon={X} label="Close" onClick={onClose} /></div><dl className="mt-6 grid grid-cols-2 gap-4 text-sm">{[['SKU',product.sku||'—'],['Status',product.status],['Price',money(product.salePrice||product.price)],['Stock',`${product.stock} ${product.unit||''}`],['Categories',product.categories.join(', ')||'—'],['Visibility',product.visibility]].map(([label,value])=><div key={label}><dt className="text-slate-500">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>)}</dl>{product.status === 'Published' && <a href={route('storefront.products.show',product.slug)} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-lg bg-violet-600 px-4 py-2 text-sm font-semibold text-white">Open storefront page</a>}</div></div>;
}

function EditModal({ product, onClose }) {
    const [form, setForm] = useState({ title:product.title, regular_price:product.price, sale_price:product.salePrice||'', stock_quantity:product.stock, status:product.status, visibility:product.visibility });
    const field = (key) => (event) => setForm({...form,[key]:event.target.value});
    const save = (event) => { event.preventDefault(); router.patch(route('inventories.products.update',product.id),form,{preserveScroll:true,onSuccess:onClose}); };
    const input = 'mt-2 h-11 w-full rounded-lg border-slate-300 text-sm focus:border-violet-500 focus:ring-violet-500';
    return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><form onSubmit={save} className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-sm font-semibold text-violet-600">Edit product</p><h2 className="mt-1 text-xl font-bold">{product.title}</h2></div><IconButton icon={X} label="Close" onClick={onClose} /></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold sm:col-span-2">Product title<input required value={form.title} onChange={field('title')} className={input}/></label><label className="text-sm font-semibold">Regular price<input required type="number" min="0" step="0.01" value={form.regular_price} onChange={field('regular_price')} className={input}/></label><label className="text-sm font-semibold">Sale price<input type="number" min="0" step="0.01" value={form.sale_price} onChange={field('sale_price')} className={input}/></label><label className="text-sm font-semibold">Stock<input required type="number" min="0" value={form.stock_quantity} onChange={field('stock_quantity')} className={input}/></label><label className="text-sm font-semibold">Status<select value={form.status} onChange={field('status')} className={input}>{['Draft','Published','Active','Inactive','Discontinued'].map(item=><option key={item}>{item}</option>)}</select></label><label className="text-sm font-semibold">Visibility<select value={form.visibility} onChange={field('visibility')} className={input}><option>Public</option><option>Private</option></select></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2 text-sm font-semibold">Cancel</button><button className="rounded-lg bg-violet-600 px-4 py-2 text-sm font-semibold text-white">Save changes</button></div></form></div>;
}

export default function ProductsIndex({ products=[] }) {
    const [query,setQuery]=useState(''); const [viewing,setViewing]=useState(null); const [editing,setEditing]=useState(null);
    const visible=useMemo(()=>products.filter(product=>`${product.title} ${product.sku||''} ${product.categories.join(' ')}`.toLowerCase().includes(query.toLowerCase())),[products,query]);
    const remove=(product)=>window.confirm(`Delete "${product.title}"? This action cannot be undone.`)&&router.delete(route('inventories.products.destroy',product.id),{preserveScroll:true});
    return <AdminLayout><Head title="Products"/><main className="-mx-4 -my-6 min-h-screen bg-[#f8f7fa] p-4 text-slate-800 sm:-mx-6 sm:p-6 lg:-mx-8 lg:-my-8 lg:p-8"><div className="mx-auto max-w-[1450px]"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-sm font-medium text-violet-600">Inventories</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Products</h1><p className="mt-1 text-sm text-slate-500">Manage published products, prices and stock.</p></div><Link href={route('inventories.products.create')} className="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white"><Plus className="size-4"/>Add new product</Link></div><section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex justify-end border-b p-4"><label className="relative w-full max-w-sm"><Search className="absolute left-3 top-3 size-4 text-slate-400"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search products" className="h-10 w-full rounded-lg border-slate-300 pl-10 text-sm"/></label></div><div className="overflow-x-auto"><table className="min-w-full"><thead><tr>{['Image','Product','SKU','Categories','Price','Stock','Status',''].map((title,index)=><th key={index} className="px-5 py-3 text-left">{title}</th>)}</tr></thead><tbody className="divide-y">{visible.map(product=><tr key={product.id} className="hover:bg-violet-50/30"><td className="px-5 py-3">{product.image?<img src={product.image} alt="" className="size-12 rounded-lg object-cover"/>:<span className="grid size-12 place-items-center rounded-lg bg-slate-100 text-slate-400"><Image className="size-5"/></span>}</td><td className="px-5 py-3"><button onClick={()=>setViewing(product)} className="font-semibold text-violet-600 hover:underline">{product.title}</button><p className="text-xs text-slate-500">/{product.slug}</p></td><td className="px-5 py-3">{product.sku||'—'}</td><td className="px-5 py-3">{product.categories.join(', ')||'—'}</td><td className="px-5 py-3"><b>{money(product.salePrice||product.price)}</b>{product.salePrice&&<span className="ml-2 text-xs text-slate-400 line-through">{money(product.price)}</span>}</td><td className="px-5 py-3">{product.stock} {product.unit||''}</td><td className="px-5 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${product.status==='Published'?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700'}`}>{product.status}</span></td><td className="px-5 py-3"><ProductActions product={product} onView={setViewing} onEdit={setEditing} onDelete={remove}/></td></tr>)}</tbody></table></div>{!visible.length&&<div className="py-16 text-center text-sm text-slate-500">No products found.</div>}</section></div></main><ViewModal product={viewing} onClose={()=>setViewing(null)}/>{editing&&<EditModal key={editing.id} product={editing} onClose={()=>setEditing(null)}/>}</AdminLayout>;
}
