import { Head, Link, usePage } from '@inertiajs/react';
import { ChevronLeft, Pencil, ShieldCheck, UserRound } from 'lucide-react';
import AdminLayout from '@/app/layouts/AdminLayout';
import { panel, StatusBadge } from '@/app/modules/access/components';

export default function RoleShow({ role }) {
    const permissions = usePage().props.auth.permissions || [], canEdit = (permissions.includes('*') || permissions.includes('roles.update')) && !role.system;
    return <AdminLayout><Head title={role.name} /><div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><Link href={route('roles.index')} className="inline-flex items-center gap-1 text-sm font-bold text-violet-600"><ChevronLeft className="size-4" />Roles & Permissions</Link><div className="mt-2 flex items-center gap-3"><h1 className="text-3xl font-black text-slate-950 dark:text-white">{role.name}</h1>{role.system && <ShieldCheck className="size-6 text-violet-600" />}</div><p className="mt-2 text-sm text-slate-500">{role.description || 'No description provided.'}</p></div>{canEdit && <Link href={route('roles.edit', role.id)} className="inline-flex h-11 items-center justify-center gap-2 rounded-lg bg-violet-600 px-4 text-sm font-bold text-white"><Pencil className="size-4" />Edit role</Link>}</div>
        <section className={`${panel} p-5`}><h2 className="text-lg font-black text-slate-900 dark:text-white">Permissions</h2><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{Object.entries(role.permissions).map(([module, actions]) => <div key={module} className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><h3 className="font-bold capitalize text-slate-900 dark:text-white">{module.replaceAll('_', ' ')}</h3><div className="mt-3 flex flex-wrap gap-2">{actions.map(action => <span key={action} className="rounded-md bg-violet-100 px-2.5 py-1 text-xs font-bold capitalize text-violet-700">{action}</span>)}</div></div>)}</div></section>
        <section className={`${panel} overflow-hidden`}><div className="border-b border-slate-200 p-5 dark:border-slate-700"><h2 className="text-lg font-black text-slate-900 dark:text-white">Assigned users ({role.users.length})</h2></div>{role.users.length ? <div className="divide-y divide-slate-200 dark:divide-slate-700">{role.users.map(user => <Link key={user.id} href={route('admin-users.show', user.id)} className="flex items-center gap-3 p-5 hover:bg-violet-50/50 dark:hover:bg-slate-800"><span className="grid size-10 place-items-center rounded-full bg-violet-100 text-violet-700"><UserRound className="size-5" /></span><span className="min-w-0 flex-1"><b className="block truncate text-sm text-slate-900 dark:text-white">{user.name}</b><span className="text-xs text-slate-500">{user.email}</span></span><StatusBadge active={user.active} /></Link>)}</div> : <p className="p-10 text-center text-sm text-slate-500">No users are assigned to this role.</p>}</section>
    </div></AdminLayout>;
}
