import { Head, Link, router } from '@inertiajs/react';
import { useState } from 'react';
import AdminLayout from '@/app/layouts/AdminLayout';
import {panel,button} from '../ui';
export default function Dashboard({counts,total,cod,collected,collectionVerified,bookings,filters}) {
    const [from,setFrom]=useState(filters.from||''),[to,setTo]=useState(filters.to||'');
    const apply=(start=from,end=to)=>router.get(route('couriers.index'),{from:start||undefined,to:end||undefined},{preserveState:true});
    const range=days=>{const end=new Date(),start=new Date();start.setDate(end.getDate()-days+1);const fmt=d=>d.toLocaleDateString('en-CA',{timeZone:'Asia/Dhaka'});setFrom(fmt(start));setTo(fmt(end));apply(fmt(start),fmt(end));};
    return <AdminLayout><Head title="Courier Dashboard"/><div className="space-y-5"><header className="flex flex-wrap justify-between gap-3"><h1>Courier Dashboard</h1><Link className="text-violet-600" href={route('couriers.settings')}>Courier Settings</Link></header><form className="flex flex-wrap items-center gap-2" onSubmit={e=>{e.preventDefault();apply();}}>{[[1,'Today'],[7,'Last 7 Days'],[30,'Last 30 Days']].map(([days,label])=><button className="rounded border px-3 py-2" type="button" key={days} onClick={()=>range(days)}>{label}</button>)}<input aria-label="From date" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input aria-label="To date" type="date" value={to} onChange={e=>setTo(e.target.value)}/><button className={button}>Filter</button></form><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Total Courier Orders',total],['Pending',counts.pending||0],['In Transit',(counts.in_transit||0)+(counts.picked||0)],['Delivered',counts.delivered||0],['Returned',counts.returned||0],['Total COD','৳'+Number(cod).toLocaleString()],['Collected COD',collectionVerified?'৳'+Number(collected).toLocaleString():'Not reconciled'],['Needs verification',counts.needs_verification||0]].map(([label,value])=><div key={label} className={panel}><p className="text-sm text-slate-500">{label}</p><b className="mt-2 block text-xl">{value}</b></div>)}</div><p className="text-xs text-slate-500">Live bookings only. Delivered parcels are not counted as COD remitted until settlement is verified.</p><div className={panel+' overflow-x-auto'}><table className="w-full text-sm"><thead><tr>{['Reference','Courier','Consignment','Status','COD','Details'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{bookings.data.map(b=><tr key={b.id}><td>{b.reference}</td><td>{b.courier.name}</td><td>{b.consignment_id||'—'}</td><td>{b.status.replaceAll('_',' ')}</td><td>৳{b.cod_amount}</td><td><Link className="text-violet-600" href={route('orders.show',b.order_id)}>View order</Link></td></tr>)}</tbody></table>{!bookings.data.length&&<p className="py-8 text-center">No courier bookings.</p>}<nav className="mt-4 flex flex-wrap gap-2">{bookings.links.map((l,i)=>l.url&&<Link key={i} className="rounded border px-3 py-2" href={l.url} dangerouslySetInnerHTML={{__html:l.label}}/>)}</nav></div></div></AdminLayout>;
}
