import { Head, Link, useForm } from '@inertiajs/react';
import { useState } from 'react';
import { Truck } from 'lucide-react';
import AdminLayout from '@/app/layouts/AdminLayout';
import { api, Field, button, panel } from '../ui';

function CourierCard({ courier, statuses }) {
    const form=useForm({active:courier.active,sandbox_mode:courier.sandbox_mode,api_url:courier.api_url,credentials:Object.fromEntries(courier.fields.map(key=>[key,''])),status_mapping:courier.status_mapping||{}});
    const [message,setMessage]=useState(''); const [testing,setTesting]=useState(false);
    return <form className={panel} onSubmit={e=>{e.preventDefault();form.patch(route('couriers.save',courier.id),{preserveScroll:true,onSuccess:()=>form.setData('credentials',Object.fromEntries(courier.fields.map(key=>[key,''])))});}}>
        <header className="mb-5 flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="rounded-xl bg-violet-50 p-3 text-violet-600"><Truck/></span><div><h2>{courier.name}</h2><span className={courier.active?'text-xs text-emerald-600':'text-xs text-slate-500'}>{courier.active?'● Active':'● Inactive'} · {courier.tested_at?'Connection tested':'Not tested'}</span></div></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" role="switch" checked={form.data.active} onChange={e=>{if(e.target.checked||window.confirm(`Are you sure you want to deactivate ${courier.name}?`))form.setData('active',e.target.checked);}}/>Active</label></header>
        <div className="grid gap-4 sm:grid-cols-2">{courier.fields.map(key=><Field key={key} label={key.replaceAll('_',' ')}><input type="password" autoComplete="new-password" value={form.data.credentials[key]} placeholder={courier.configured.includes(key)?'Configured — leave blank to retain':'Not configured'} onChange={e=>form.setData('credentials',{...form.data.credentials,[key]:e.target.value})}/></Field>)}
        <Field label="Mode"><select value={form.data.sandbox_mode?'sandbox':'live'} onChange={e=>{const sandbox=e.target.value==='sandbox';form.setData({...form.data,sandbox_mode:sandbox,api_url:sandbox?courier.sandboxUrl:courier.liveUrl});}}><option value="live">Live</option>{courier.sandboxUrl&&<option value="sandbox">Sandbox</option>}</select></Field><Field label="API URL"><input value={form.data.api_url} onChange={e=>form.setData('api_url',e.target.value)}/></Field></div>
        {!courier.sandboxUrl&&<p className="mt-3 text-xs text-slate-500">Sandbox is not available for this provider.</p>}
        <details className="mt-5"><summary className="cursor-pointer font-medium">Courier → Order status mapping</summary><p className="my-3 text-xs text-slate-500">Leave unmapped to review manually. Payment status is not changed by delivery status.</p><div className="grid gap-3 sm:grid-cols-2">{statuses.map(status=><Field label={status.replaceAll('_',' ')} key={status}><select value={form.data.status_mapping[status]||''} onChange={e=>form.setData('status_mapping',{...form.data.status_mapping,[status]:e.target.value})}><option value="">Do not change order</option>{['confirmed','processing','ready_to_ship','shipped','completed','returned','cancelled'].map(s=><option key={s} value={s}>{s}</option>)}</select></Field>)}</div></details>
        {Object.values(form.errors).map((error,i)=><p key={i} role="alert" className="mt-2 text-sm text-rose-600">{error}</p>)}{message&&<p role="status" className="mt-3 text-sm">{message}</p>}
        <div className="mt-5 flex gap-3"><button disabled={form.processing} className={button}>Save Settings</button><button type="button" disabled={testing||form.processing} className="rounded-lg border px-4 py-2" onClick={async()=>{setTesting(true);try{setMessage((await api(route('couriers.test',courier.id),{})).message);}catch(e){setMessage(e.message);}finally{setTesting(false);}}}>{testing?'Testing…':'Test saved connection'}</button></div>
    </form>;
}
export default function Settings({couriers,statuses}) { return <AdminLayout><Head title="Courier Integration"/><div className="space-y-6"><header><p className="text-violet-600">Settings</p><h1>Courier Integration</h1><Link className="text-violet-600" href={route('couriers.index')}>Courier dashboard →</Link></header><div className="grid items-start gap-5 xl:grid-cols-2">{couriers.map(c=><CourierCard key={c.id} courier={c} statuses={statuses}/>)}</div></div></AdminLayout>; }
