import { Head, Link, router } from '@inertiajs/react';
import { CalendarDays, Clock, Eye, Mail, NotebookPen, Package, Phone, Plus, Search } from 'lucide-react';
import { useState } from 'react';
import AdminLayout from '@/app/layouts/AdminLayout';

const money = value => `BDT ${Number(value || 0).toLocaleString('en-BD', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const statuses = ['Pending', 'Confirmed', 'Processing', 'Ready to Ship', 'Shipped', 'Completed', 'Cancelled', 'Returned'];
const statusKey = value => value.toLowerCase().replaceAll(' ', '_');
const statusStyle = { Pending: 'border-amber-200 bg-amber-50 text-amber-700', Confirmed: 'border-cyan-200 bg-cyan-50 text-cyan-700', Processing: 'border-sky-200 bg-sky-50 text-sky-700', 'Ready to Ship': 'border-violet-200 bg-violet-50 text-violet-700', Shipped: 'border-blue-200 bg-blue-50 text-blue-700', Completed: 'border-emerald-200 bg-emerald-50 text-emerald-700', Cancelled: 'border-rose-200 bg-rose-50 text-rose-700', Returned: 'border-orange-200 bg-orange-50 text-orange-700' };

export default function OrdersIndex({ orders = [], filters = {}, statusCounts = {}, pagination = {} }) {
    const [query, setQuery] = useState(filters.q || '');
    const [dateFrom, setDateFrom] = useState(filters.dateFrom || '');
    const [dateTo, setDateTo] = useState(filters.dateTo || '');
    const applyFilters = changes => router.get(route('orders.index'), { q: query || undefined, status: filters.status || undefined, date_from: dateFrom || undefined, date_to: dateTo || undefined, per_page: filters.perPage || 25, ...changes }, { preserveState: true, preserveScroll: true, replace: true });
    const count = item => Number(statusCounts[statusKey(item)] || 0);

    return <AdminLayout><Head title="Orders" /><main className="-mx-4 -my-6 min-h-screen bg-[#f8f7fa] p-4 text-slate-800 dark:bg-slate-950 dark:text-slate-100 sm:-mx-6 sm:p-6 lg:-mx-8 lg:-my-8 lg:p-8"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <div className="flex flex-col justify-between gap-4 px-6 py-5 sm:flex-row sm:items-center"><div><h1 className="text-lg font-bold">Orders Management</h1><p className="mt-1 text-sm text-slate-500">Manage and track all orders</p></div><Link href={route('orders.create')} className="inline-flex items-center justify-center gap-2 rounded-xl bg-violet-600 px-5 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-violet-700"><Plus className="size-4" />New Order</Link></div>
        <div className="grid gap-3 px-6 pb-6 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">{statuses.map(item => { const key=statusKey(item); return <button key={item} onClick={() => applyFilters({ status: filters.status===key?undefined:key, page:1 })} className={`flex items-center justify-between rounded-xl border px-3 py-3 text-left text-xs font-semibold ${statusStyle[item]} ${filters.status===key ? 'ring-2 ring-violet-500 ring-offset-1' : ''}`}><span>{item}</span><b className="text-xl">{count(item)}</b></button>; })}</div>
        <form onSubmit={event=>{event.preventDefault();applyFilters({q:query||undefined,date_from:dateFrom||undefined,date_to:dateTo||undefined,page:1})}} className="grid gap-3 border-y border-slate-200 bg-slate-50/80 p-5 md:grid-cols-2 xl:grid-cols-[minmax(260px,1fr)_170px_170px_180px_100px]"><label className="relative"><Search className="pointer-events-none absolute left-3 top-3 size-4 text-slate-400"/><input value={query} onChange={event=>setQuery(event.target.value)} className="h-11 w-full rounded-xl border-slate-200 bg-white pl-10 text-sm" placeholder="Search by order ID, customer or phone…"/></label><label className="relative"><span className="pointer-events-none absolute left-3 top-1.5 text-[10px] font-bold uppercase tracking-wide text-slate-400">From</span><input aria-label="From date" type="date" value={dateFrom} max={dateTo||undefined} onChange={event=>setDateFrom(event.target.value)} className="h-11 w-full rounded-xl border-slate-200 bg-white pb-1 pl-14 pt-4 text-sm"/></label><label className="relative"><span className="pointer-events-none absolute left-3 top-1.5 text-[10px] font-bold uppercase tracking-wide text-slate-400">To</span><input aria-label="To date" type="date" value={dateTo} min={dateFrom||undefined} onChange={event=>setDateTo(event.target.value)} className="h-11 w-full rounded-xl border-slate-200 bg-white pb-1 pl-10 pt-4 text-sm"/></label><select value={filters.status||''} onChange={event=>applyFilters({status:event.target.value||undefined,page:1})} className="h-11 rounded-xl border-slate-200 bg-white text-sm"><option value="">All Status</option>{statuses.map(item=><option key={item} value={statusKey(item)}>{item}</option>)}</select><button className="h-11 rounded-xl bg-slate-900 text-sm font-bold text-white hover:bg-slate-800">Filter</button></form>
        <div className="overflow-x-auto"><table className="w-full min-w-[1080px] text-left text-sm"><thead className="bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr>{['Order','Customer','Delivery','Products','Amount','Status','Date','Actions'].map(heading=><th key={heading} className="px-5 py-4">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-200">{orders.map(order=><tr key={order.id} className={!order.viewed?'bg-violet-50/70':'bg-white'}>
            <td className="px-5 py-5"><Link href={route('orders.show',order.id)} className="font-bold text-violet-600 hover:underline">{order.number}</Link><div className="mt-2 flex flex-col items-start gap-1.5"><span className="inline-flex items-center gap-1 text-[11px] text-slate-500"><Package className="size-3.5"/>{order.itemCount} {Number(order.itemCount)===1?'item':'items'}</span><span title={order.note||'No order note'} className={order.note?'inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700':'inline-flex items-center gap-1 rounded-full bg-slate-100 px-2 py-1 text-[10px] text-slate-500'}><NotebookPen className="size-3"/>{order.note?'Read before confirm':'No note'}</span></div></td>
            <td className="px-5 py-5"><b>{order.customer}</b><small className="mt-1 flex items-center gap-1.5 text-slate-500"><Phone className="size-3.5"/>{order.phone}</small><small className="mt-1 flex items-center gap-1.5 text-slate-400"><Mail className="size-3.5"/>{order.email}</small></td><td className="max-w-[180px] px-5 py-5 text-slate-500">{order.delivery}</td><td className="max-w-[190px] px-5 py-5">{(order.products||[]).map((product,index)=><span key={`${product.slug||product.name}-${index}`}>{index>0&&', '}{product.slug?<a href={route('storefront.products.show',product.slug)} target="_blank" rel="noopener noreferrer" className="text-violet-700 hover:underline">{product.name}</a>:product.name}</span>)}</td>
            <td className="min-w-[180px] px-5 py-5"><div className="space-y-1 text-xs"><div className="flex justify-between gap-4 text-slate-500"><span>Products</span><b>{money(order.subtotal)}</b></div><div className="flex justify-between gap-4 text-slate-500"><span>{order.deliveryZone==='inside_dhaka'?'Inside Dhaka':'Outside Dhaka'}</span><b>{Number(order.shipping)>0?money(order.shipping):'Free'}</b></div><div className="flex justify-between border-t pt-2 text-sm"><strong>Total</strong><strong className="text-violet-700">{money(order.total)}</strong></div></div></td><td className="px-5 py-5"><span className={`rounded-full border px-3 py-1 text-xs font-semibold ${statusStyle[order.status]}`}>{order.status}</span></td><td className="px-5 py-5"><span className="flex items-center gap-2 whitespace-nowrap text-xs text-slate-500"><CalendarDays className="size-3.5 text-violet-500"/>{order.date}</span><small className="mt-2 flex items-center gap-2 text-slate-400"><Clock className="size-3.5 text-sky-500"/>{order.time}</small></td><td className="px-5 py-5"><Link href={route('orders.show',order.id)} title="View order" className="grid size-9 place-items-center rounded-full bg-violet-50 text-violet-600 hover:bg-violet-100"><Eye className="size-4"/></Link></td>
        </tr>)}{orders.length===0&&<tr><td colSpan="8" className="px-5 py-14 text-center text-slate-500">No orders match your filters.</td></tr>}</tbody></table></div>
        <div className="flex flex-col gap-3 border-t border-slate-200 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-slate-500">Showing <b className="text-slate-700">{pagination.from||0}–{pagination.to||0}</b> of <b className="text-slate-700">{pagination.total||0}</b> orders</p><div className="flex items-center gap-2"><select value={filters.perPage||25} onChange={event=>applyFilters({per_page:Number(event.target.value),page:1})} className="h-9 rounded-lg border-slate-200 text-xs"><option value="25">25 / page</option><option value="50">50 / page</option><option value="100">100 / page</option></select><button type="button" disabled={pagination.currentPage<=1} onClick={()=>applyFilters({page:pagination.currentPage-1})} className="h-9 rounded-lg border px-3 text-xs font-bold disabled:opacity-40">Previous</button><span className="px-2 text-xs font-bold">{pagination.currentPage||1} / {pagination.lastPage||1}</span><button type="button" disabled={pagination.currentPage>=pagination.lastPage} onClick={()=>applyFilters({page:pagination.currentPage+1})} className="h-9 rounded-lg border px-3 text-xs font-bold disabled:opacity-40">Next</button></div></div>
    </section></main></AdminLayout>;
}
