<?php
namespace App\Modules\Settings\Http\Controllers;
use App\Http\Controllers\Controller;use App\Modules\Settings\Models\CommunicationSetting;use App\Services\MramSmsService;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Mail;use Illuminate\Validation\Rule;use Inertia\Inertia;use Inertia\Response;
class CommunicationSettingController extends Controller
{
 public function edit():Response{$s=CommunicationSetting::firstOrCreate(['id'=>1]);return Inertia::render('app/modules/settings/pages/Communication',['settings'=>['emailEnabled'=>$s->email_enabled,'mailHost'=>$s->mail_host,'mailPort'=>$s->mail_port,'mailUsername'=>$s->mail_username,'hasMailPassword'=>filled($s->mail_password),'mailEncryption'=>$s->mail_encryption,'mailFromAddress'=>$s->mail_from_address,'mailFromName'=>$s->mail_from_name,'smsEnabled'=>$s->sms_enabled,'hasMramApiKey'=>filled($s->mram_api_key),'mramSenderId'=>$s->mram_sender_id]]);}
 public function update(Request $request):RedirectResponse{$data=$request->validate(['email_enabled'=>['boolean'],'mail_host'=>['nullable','string','max:255'],'mail_port'=>['required','integer','between:1,65535'],'mail_username'=>['nullable','string','max:255'],'mail_password'=>['nullable','string','max:500'],'mail_encryption'=>['required',Rule::in(['tls','ssl','none'])],'mail_from_address'=>['nullable','email','max:255'],'mail_from_name'=>['nullable','string','max:255'],'sms_enabled'=>['boolean'],'mram_api_key'=>['nullable','string','max:500'],'mram_sender_id'=>['nullable','string','max:100']]);$s=CommunicationSetting::firstOrCreate(['id'=>1]);if(blank($data['mail_password']??null))unset($data['mail_password']);if(blank($data['mram_api_key']??null))unset($data['mram_api_key']);$s->update($data);return back()->with('success','Communication settings saved.');}
 public function testEmail(Request $request):RedirectResponse{$data=$request->validate(['email'=>['required','email']]);$this->apply();Mail::raw('Your '.config('app.name').' email integration is working correctly.',fn($mail)=>$mail->to($data['email'])->subject('Email integration test'));return back()->with('success','Test email sent successfully.');}
 public function testSms(Request $request,MramSmsService $sms):RedirectResponse{$data=$request->validate(['phone'=>['required','regex:/^\\+?[0-9]{10,15}$/']]);$this->apply();$sms->send($data['phone'],'Your '.config('app.name').' SMS integration is working correctly.');return back()->with('success','Test SMS sent successfully.');}
 private function apply():void{$s=CommunicationSetting::find(1);abort_unless($s,422);config(['mail.default'=>'smtp','mail.mailers.smtp.host'=>$s->mail_host,'mail.mailers.smtp.port'=>$s->mail_port,'mail.mailers.smtp.username'=>$s->mail_username,'mail.mailers.smtp.password'=>$s->mail_password,'mail.mailers.smtp.encryption'=>$s->mail_encryption==='none'?null:$s->mail_encryption,'mail.from.address'=>$s->mail_from_address,'mail.from.name'=>$s->mail_from_name,'services.mram.api_key'=>$s->mram_api_key,'services.mram.sender_id'=>$s->mram_sender_id]);app('mail.manager')->forgetMailers();}
}