import { Head, router, useForm, usePage } from '@inertiajs/react';
import { useState } from 'react';
import { Pencil, Plus, Trash2 } from 'lucide-react';
import AdminLayout from '@/app/layouts/AdminLayout';
import Dialog from '@/app/design-system/components/Dialog';
import RichTextEditor from '@/app/design-system/components/RichTextEditor';
import { Panel, Field, Errors, ImagePicker, categoryOptions, input, button, secondary, slugify, imageUrl } from './shared';

export function CategoryModal({ category, categories, close }) {
    const form = useForm({ name: category?.name || '', slug: category?.slug || '', parent_id: category?.parent_id || '', description: category?.description || '', image_path: category?.image_path || null });
    const [custom, setCustom] = useState(Boolean(category));
    const submit = e => { e.preventDefault(); form[category ? 'patch' : 'post'](category ? route('blog.categories.update', category.id) : route('blog.categories.store'), { onSuccess: close }); };
    return <Dialog open onClose={close} title={category ? 'Edit blog category' : 'Add blog category'}><form onSubmit={submit} className="max-h-[75vh] space-y-4 overflow-y-auto p-5"><Errors errors={form.errors}/><Field label="Name"><input required className={input} value={form.data.name} onChange={e => form.setData({ ...form.data, name: e.target.value, slug: custom ? form.data.slug : slugify(e.target.value) })}/></Field><Field label="Permalink slug"><input required className={input} value={form.data.slug} onChange={e => { setCustom(true); form.setData('slug', slugify(e.target.value)); }}/></Field><Field label="Parent category"><select className={input} value={form.data.parent_id} onChange={e => form.setData('parent_id', e.target.value)}><option value="">None</option>{categoryOptions(categories).filter(c => c.id !== category?.id).map(c => <option key={c.id} value={c.id}>{'— '.repeat(c.depth)}{c.name}</option>)}</select></Field><Field label="Description"><RichTextEditor value={form.data.description} onChange={v => form.setData('description', v)}/></Field><ImagePicker value={form.data.image_path} onChange={v => form.setData('image_path', v)}/><button disabled={form.processing} className={button}>Save category</button></form></Dialog>;
}
export default function Categories({ categories }) {
    const [modal, setModal] = useState(false), [selected, setSelected] = useState(null), [search, setSearch] = useState('');
    const { errors } = usePage().props;
    return <AdminLayout><Head title="Blog categories"/><div className="mb-6 flex items-center justify-between"><div><p className="text-sm text-violet-600">Blog</p><h1 className="text-2xl font-bold">Categories</h1></div><button className={button} onClick={() => { setSelected(null); setModal(true); }}><Plus size={16}/>Add category</button></div><Errors errors={errors || {}}/><Panel><input aria-label="Search categories" placeholder="Search categories…" className={`${input} mb-5 max-w-sm`} value={search} onChange={e => setSearch(e.target.value)}/><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-slate-500"><tr>{['Category', 'Permalink', 'Blogs', 'Actions'].map(t => <th key={t} className="p-3">{t}</th>)}</tr></thead><tbody>{categoryOptions(categories).filter(c => c.name.toLowerCase().includes(search.toLowerCase())).map(c => <tr key={c.id} className="border-b border-slate-100 dark:border-slate-800"><td className="p-3"><div className="flex items-center gap-3" style={{ paddingLeft: c.depth * 16 }}>{c.image_path && <img className="size-10 rounded-lg object-cover" src={imageUrl(c.image_path)} alt=""/>}<b>{c.name}</b></div></td><td className="p-3">/blog/category/{c.slug}</td><td className="p-3">{c.posts_count}</td><td className="p-3"><div className="flex gap-2"><button aria-label={`Edit ${c.name}`} className={secondary} onClick={() => { setSelected(c); setModal(true); }}><Pencil size={16}/></button><button aria-label={`Delete ${c.name}`} className={secondary} onClick={() => { if (confirm(`Delete category ${c.name}?`)) router.delete(route('blog.categories.destroy', c.id)); }}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table>{!categories.length && <p className="p-8 text-center text-slate-500">No blog categories yet.</p>}</div></Panel>{modal && <CategoryModal category={selected} categories={categories} close={() => setModal(false)}/>}</AdminLayout>;
}
