import { Link, router } from '@inertiajs/react';
import { useState } from 'react';
import StorefrontLayout from '@/app/layouts/StorefrontLayout';
import Seo from '@/app/components/Seo';
import { Pagination, imageUrl, date, input, button } from './shared';

export default function PublicIndex({ posts, categories, category, author, search }) {
    const [query, setQuery] = useState(search);
    return <StorefrontLayout><Seo title={author ? `${author.name} — Blog` : category ? `${category.name} — Blog` : 'Blog'} description={author?.bio || 'Stories, practical guides and product advice.'}/><main className="mx-auto max-w-7xl px-4 py-10 text-slate-900 dark:text-slate-100"><Link className="text-sm font-semibold text-violet-600" href={route('blog.public.index')}>Blog</Link>{author ? <header className="my-6 flex flex-wrap items-center gap-5 rounded-2xl bg-violet-50 p-6 dark:bg-slate-800">{author.image_path && <img src={imageUrl(author.image_path)} alt={author.name} className="size-24 rounded-full object-cover"/>}<div className="max-w-2xl"><h1 className="text-3xl font-bold">{author.name}</h1><p className="mt-1 text-violet-600">{author.designation}</p><p className="mt-3 whitespace-pre-line text-sm leading-6">{author.bio}</p><div className="mt-3 flex gap-4">{Object.entries(author.social_links || {}).filter(([, url]) => url).map(([label, url]) => <a key={label} href={url} target="_blank" rel="noopener noreferrer" className="text-sm text-violet-600">{label} ↗</a>)}</div></div></header> : <header className="my-6"><h1 className="text-3xl font-bold">{category?.name || 'Stories & Guides'}</h1>{category?.description ? <div className="rich-text-content mt-3" dangerouslySetInnerHTML={{ __html: category.description }}/> : <p className="mt-3 text-slate-500">Ideas, advice and useful tips from our team.</p>}</header>}<form className="mb-6 flex max-w-xl items-end gap-3" onSubmit={e => { e.preventDefault(); router.get(window.location.pathname, { search: query }); }}><input aria-label="Search articles" className={input} placeholder="Search articles…" value={query} onChange={e => setQuery(e.target.value)}/><button className={button}>Search</button></form><nav aria-label="Blog categories" className="mb-8 flex flex-wrap gap-2">{categories.map(c => <Link key={c.id} className="rounded-full bg-violet-50 px-3 py-1.5 text-sm text-violet-700 dark:bg-slate-800 dark:text-violet-300" href={route('blog.public.category', c.slug)}>{c.name}</Link>)}</nav><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{posts.data.map(p => <article key={p.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900"><Link href={route('blog.public.show', p.slug)}>{p.image_path && <img loading="lazy" src={imageUrl(p.image_path)} alt={p.title} className="aspect-[16/9] w-full object-cover"/>}<div className="p-5"><p className="text-xs text-slate-500">{date(p.published_at)} · {p.author?.name}</p><h2 className="mt-3 text-xl font-bold">{p.title}</h2><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-500">{p.excerpt}</p><span className="mt-5 inline-block text-sm font-bold text-violet-600">Read article →</span></div></Link></article>)}</div>{!posts.data.length && <p className="py-16 text-center text-slate-500">No published articles found.</p>}<Pagination links={posts.links}/></main></StorefrontLayout>;
}
