<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Installation complete</title>
    <style>*{box-sizing:border-box}body{margin:0;display:grid;min-height:100vh;place-items:center;background:radial-gradient(circle at 50% 0,#ede9fe,transparent 34rem),#f8fafc;color:#111827;font:500 14px/1.55 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}.card{width:min(560px,calc(100% - 28px));border:1px solid #e2e8f0;border-radius:20px;background:#fff;padding:34px;box-shadow:0 24px 70px #0f172a12;text-align:center}.icon{display:grid;width:64px;height:64px;margin:0 auto 20px;place-items:center;border-radius:999px;background:#ecfdf5;color:#047857;font-size:30px;font-weight:900}.eyebrow{margin:0 0 7px;color:#6d28d9;font-size:11px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}h1{margin:0;font-size:29px;letter-spacing:-.03em}p{margin:10px 0;color:#64748b}.account{margin:22px 0;border:1px solid #e2e8f0;border-radius:12px;background:#f8fafc;padding:13px;text-align:left}.account small{display:block;color:#64748b}.account b{display:block;margin-top:2px}.warning{margin:16px 0;border:1px solid #fde68a;border-radius:11px;background:#fffbeb;padding:11px 13px;color:#92400e;text-align:left}.warning ul{margin:6px 0 0;padding-left:18px}.actions{display:grid;grid-template-columns:1fr 1fr;gap:11px;margin-top:23px}.button{display:flex;min-height:44px;align-items:center;justify-content:center;border:1px solid #cbd5e1;border-radius:10px;color:#334155;font-weight:750;text-decoration:none}.button.primary{border-color:#7c3aed;background:#7c3aed;color:#fff}@media(max-width:520px){.card{padding:26px 18px}.actions{grid-template-columns:1fr}}</style>
</head>
<body><main class="card"><div class="icon">✓</div><p class="eyebrow">Installation complete</p><h1>Your store is ready</h1><p>Database migrations, store settings, permissions and the administrator account were created successfully. The installer is now locked.</p><div class="account"><small>Administrator email</small><b>{{ $adminEmail }}</b></div>@if(count($warnings))<div class="warning"><b>One manual action remains:</b><ul>@foreach($warnings as $warning)<li>{{ $warning }}</li>@endforeach</ul></div>@endif<div class="actions"><a class="button" href="{{ url('/') }}">View storefront</a><a class="button primary" href="{{ route('admin.login') }}">Open admin login</a></div></main></body>
</html>
